#!/usr/bin/env node
"use strict";
const fs=require("fs"),vm=require("vm"),path=require("path"),assert=require("assert");
function load(rel){vm.runInThisContext(fs.readFileSync(path.resolve(process.cwd(),rel),"utf8"),{filename:rel});}
const SCENE_ID="origin_academy_kakashi_anbu_retrieval",RETURN_BEAT="kak_scene04a_stop_assassin_return",PENDING_BEAT="kak_seq_debrief_pending",BATTLE_CONFIG="academy_kakashi_origin_battle_mi_1v1",BINDING="academy_kakashi.battle.stop_assassin",SOURCE_ANCHOR="AK_SA_019";
const occurrences=new Map();
globalThis.playerData={activityHistory:[]};globalThis.savePlayerData=()=>true;globalThis.normalizeStorySceneBeat=beat=>beat;
globalThis.SC_ALPHA_ORIGIN_32900={
 findOccurrence:id=>occurrences.get(String(id))||null,
 commitOccurrence:(originId,id,fact,_effects,meta)=>{id=String(id);const existing=occurrences.get(id);if(existing)return{success:true,idempotent:true,record:existing};const record={occurrenceId:id,originId,committed:true,fact,storySceneInstanceId:fact&&fact.storySceneInstanceId||null,meta};occurrences.set(id,record);playerData.activityHistory.push(record);return{success:true,idempotent:false,record};}
};
const returnBeat={beatId:RETURN_BEAT,mode:"post_battle",environmentRef:{assetId:"kakashi_origin_fight_at_sakura_tree"},text:"",nextBeatId:null,exitScene:false,allowPresentationClose:false,onEnterConsequences:[],choices:[]};
const pendingBeat={beatId:PENDING_BEAT,mode:"narration",text:"pending",nextBeatId:null,exitScene:false,allowPresentationClose:false,onEnterConsequences:[],choices:[]};
const definition={sceneId:SCENE_ID,beatMap:new Map([[RETURN_BEAT,returnBeat],[PENDING_BEAT,pendingBeat]]),onCompleteConsequences:[]};
const active={sceneId:SCENE_ID,instanceId:"qa-scene05al",beatId:RETURN_BEAT,localContext:{kakashiScene04ABattleIntentResolved:true},battleResume:{authored:null}};
globalThis.getStorySceneDefinition=id=>id===SCENE_ID?definition:null;globalThis.getActiveStorySceneRuntime=()=>active;globalThis.getStoryScenePerformance33900=()=>null;globalThis.renderStoryScenePresentationLayer=()=>true;
globalThis.advanceStoryScene=function(choiceId=null){const beat=definition.beatMap.get(active.beatId);if(!beat)return{success:false,reason:"qa_beat_missing"};if(beat.mode==="narration"){if(!beat.nextBeatId)return{success:false,reason:"qa_next_missing"};active.beatId=beat.nextBeatId;return{success:true,beatId:active.beatId};}if(beat.mode==="choice"){const row=(beat.choices||[]).find(x=>x&&x.choiceId===choiceId);if(!row)return{success:false,reason:"qa_choice_missing"};for(const req of row.consequenceRequests||[]){const out=req.resolve();if(!out||out.success!==true)return out||{success:false,reason:"qa_choice_consequence_failed"};}active.beatId=row.nextBeatId;return{success:true,beatId:active.beatId};}return{success:false,reason:"qa_mode_not_supported",mode:beat.mode};};
globalThis.SC_ALPHA_KAKASHI_SCENE04A_35710={patchId:"qa-scene04a"};globalThis.commitAcademyKakashiTerminalDebriefRewards34800=()=>({success:true});globalThis.getAcademyKakashiOriginRewardSnapshot34800=()=>({rewardSources:{},receipts:{},grants:{}});
load("runtime/alpha-story-decision-realisation-34000.js");
globalThis.SC_ALPHA_KAKASHI_FINAL_34100={recordPostResolutionState:({participantStates=[],materialStates=[]}={})=>{const results=[];for(const row of participantStates)results.push(SC_STORY_DECISION_REALISATION_34000.recordParticipantClassification({storyUnitRef:"academy_kakashi",...row}));for(const row of materialStates)results.push(SC_STORY_DECISION_REALISATION_34000.recordMaterialState({storyUnitRef:"academy_kakashi",...row}));return{success:results.every(x=>x&&x.success===true),results};},terminalGuard:state=>SC_STORY_DECISION_REALISATION_34000.terminalSemanticGuard({storyUnitRef:"academy_kakashi",state,requiredMaterialRefs:Array.isArray(state&&state.materiallyRelevantRefs)?state.materiallyRelevantRefs:[]})};
load("runtime/alpha-kakashi-terminal-debrief-35100.js");load("runtime/alpha-kakashi-scene05a-l-35750.js");
const MOD=SC_ALPHA_KAKASHI_SCENE05AL_35750;assert(MOD);assert.strictEqual(MOD.authority,"aa88db471b71a305ec34e01ff0e094ac26f1638f");assert.strictEqual(MOD.cueCount,27);assert.strictEqual(MOD.objectiveInitial,"Retrieve the package.");assert.strictEqual(MOD.objectiveAfter,"Return to ANBU.");
const diag=runAcademyKakashiScene05AL35750Diagnostics();assert.strictEqual(diag.pass,true,"Scene 05A-L diagnostics failed: "+JSON.stringify(diag.failed));
const exact=["The opening is small.","Masked Interceptor takes it.","Kakashi hits the stone beneath the Sakura tree.","Before he can recover, she is on him.","His arm is forced behind his back.","His shoulder pinned.","Kakashi twists once.","She tightens the hold.","Enough to stop him.","Then her attention shifts.","Not to Kakashi.","Down the street.","Toward the route Package Smuggler took.","The pressure disappears.","Kakashi turns his head just in time to see Masked Interceptor break away.","She runs.","Fast.","After Package Smuggler.","Kakashi forces himself back to his feet.","By then she is gone.","So is Package Smuggler.","The package went with him.","ANBU Marked Target disappeared even earlier.","Kakashi looks down the empty street.","No trail.","No one left to follow.","The package is beyond his reach now."];
function battleResult(resultState){return{battleConfigId:BATTLE_CONFIG,battleOccurrenceId:"qa-mi-loss-1",storyOccurrenceId:active.instanceId,sourceAnchorRef:SOURCE_ANCHOR,bindingRef:BINDING,resultState,playerActionOpportunityCount:4,participants:[{participantRef:"academy_kakashi",side:"player",battleStatus:resultState==="opposition_side_victory"?"defeated":"active",lifeState:"unresolved",custodyState:"unresolved"},{participantRef:"academy_kakashi_origin_masked_interceptor",side:"opposition",battleStatus:resultState==="opposition_side_victory"?"active":"defeated",lifeState:"unresolved",custodyState:"unresolved"}],rewardGranted:false,lootGranted:false,participantDeathCommitted:false,participantCustodyCommitted:false,packageCustodyDelta:"none"};}
const entry=returnBeat.onEnterConsequences.find(x=>x&&x.requestId==="kakashi_scene05al_defeat_entry_35750");assert(entry);
active.battleResume.authored=battleResult("player_side_victory");let routed=entry.resolve();assert.strictEqual(routed.success,true);assert.strictEqual(routed.routed,false);assert.strictEqual(active.beatId,RETURN_BEAT);
active.battleResume.authored=battleResult("opposition_side_victory");routed=entry.resolve();assert.strictEqual(routed.success,true);assert.strictEqual(routed.routed,true);assert.strictEqual(active.beatId,MOD.lossBeatId);assert(active.localContext.kakashiScene05ALPackageOccurrenceId);
const occ=occurrences.get(active.localContext.kakashiScene05ALPackageOccurrenceId);assert(occ&&occ.committed);assert.strictEqual(occ.fact.kakashiDefeated,true);assert.strictEqual(occ.fact.kakashiRestrainedByMaskedInterceptor,true);assert.strictEqual(occ.fact.packageSmugglerEscapedWithPackage,true);assert.strictEqual(occ.fact.anbuMarkedTargetEscaped,true);assert.strictEqual(occ.fact.maskedInterceptorLeftKakashiSight,true);assert.strictEqual(occ.fact.maskedInterceptorPursuingPackageSmuggler,true);assert.strictEqual(occ.fact.maskedInterceptorPackageSmugglerOutcomeKnownToKakashi,false);assert.strictEqual(occ.fact.packageRecoveryAvailable,false);assert.strictEqual(occ.fact.pursuitAvailable,false);assert.strictEqual(occ.fact.pakkunInvolved,false);assert.deepStrictEqual(occ.fact.packageState,{objectRef:"kakashi_origin_outer_route_packet",currentHolderClass:"PACKAGE_SMUGGLER",recovered:false});
let snap=SC_STORY_DECISION_REALISATION_34000.getStoryUnitSnapshot("academy_kakashi");assert.strictEqual(snap.materialStates.kakashi_origin_outer_route_packet.resolved,true);assert.strictEqual(snap.materialStates.kakashi_origin_outer_route_packet.value.holderClass,"PACKAGE_SMUGGLER");
for(let i=0;i<exact.length;i++){const p=getStoryScenePerformance33900();assert(p);assert.strictEqual(p.index,i);assert.strictEqual(p.cue.kind,"narration");assert.strictEqual(p.cue.text,exact[i]);assert.strictEqual(p.cue.speakerName,undefined);if(i<exact.length-1){const out=advanceStoryScene();assert.strictEqual(out.success,true);assert.strictEqual(active.beatId,MOD.lossBeatId);assert.strictEqual(active.localContext.kakashiScene05ALObjective,"Retrieve the package.");}}
const toChoice=advanceStoryScene();assert.strictEqual(toChoice.success,true);assert.strictEqual(active.beatId,MOD.choiceBeatId);assert.strictEqual(active.localContext.kakashiScene05ALObjective,"Return to ANBU.");
const choice=definition.beatMap.get(MOD.choiceBeatId);assert.strictEqual(choice.environmentRef.assetId,"kakashi_origin_fight_at_sakura_tree");assert.strictEqual(choice.objectiveText,"Return to ANBU.");assert.deepStrictEqual(choice.choices.map(x=>x.label),["RETURN TO ANBU"]);assert.strictEqual(choice.choices[0].nextBeatId,PENDING_BEAT);
const before=occurrences.size;const returned=advanceStoryScene("scene05al_return_to_anbu");assert.strictEqual(returned.success,true);assert.strictEqual(active.beatId,PENDING_BEAT);assert.strictEqual(occurrences.size,before);assert.strictEqual(active.localContext.kakashiScene05ALReturnToAnbuChosen,true);
const terminal=SC_ALPHA_KAKASHI_TERMINAL_DEBRIEF_35100.deriveTerminalFacts();assert.strictEqual(terminal.success,true,"Terminal facts not derivable: "+JSON.stringify(terminal));assert.strictEqual(terminal.packageRecovered,false);assert.strictEqual(terminal.packageState.holderClass,"PACKAGE_SMUGGLER");assert.strictEqual(terminal.materiallyParticipatedInPlBattle,true);assert.strictEqual(terminal.pakkunPresentAtDebrief,false);assert.strictEqual(terminal.battleFacts.length,1);assert.strictEqual(terminal.battleFacts[0].battleConfigId,BATTLE_CONFIG);assert.strictEqual(terminal.battleFacts[0].resultState,"opposition_side_victory");
console.log("Academy Kakashi Scene 05A-L 35750 QA: PASS");
console.log("- exact 27-cue locked defeat narration / no dialogue");
console.log("- Objective switches Retrieve the package. -> Return to ANBU. after aftermath");
console.log("- exact factual loss closure; no pursuit / no Pakkun / downstream MI-PS outcome unknown");
console.log("- only RETURN TO ANBU; board is not auto-skipped");
console.log("- terminal debrief consumes PACKAGE_SMUGGLER holder fact and MI loss Battle participation");
