'use strict';
const fs=require('fs'),vm=require('vm'),path=require('path');
const ROOT=path.resolve(__dirname,'..');
const files=['core','a','b','c','integrator'].map(n=>path.join(ROOT,'runtime',`alpha-origin-scenes-32900-${n}.js`));
const scenes=new Map([['origin_academy_menma_prologue',{sceneId:'origin_academy_menma_prologue',beats:[{beatId:'menma'}],beatMap:new Map([['menma',{beatId:'menma'}]])}]]);
const receipts=[];const completions=[];let active=null;
const expectedSource={
'HIN-01':'occ_origin_hinata_controlled_hyuga_spar_resolution','HIN-02':'occ_origin_hinata_younger_student_practice_resolution','HIN-03':'occ_origin_hinata_younger_student_practice_resolution',
'IZU-01':'occ_origin_izuno_pursuit_tracking_resolution','IZU-02':'occ_origin_izuno_intercept_prediction_resolution','IZU-03':'occ_origin_izuno_pursuit_cooperation_resolution','IZU-04':'occ_origin_izuno_rogue_genin_interruption_resolution',
'MIR-01':'occ_origin_mirai_substitution_verification_resolution','MIR-02':'occ_origin_mirai_changed_chakra_observation','MIR-03':'occ_origin_mirai_checkpoint_escort_resolution',
'KUS-01':'occ_origin_kushina_residual_seal_work_resolution','KUS-02':'occ_origin_kushina_gerotora_identity_disclosure','KUS-03':'occ_origin_kushina_gerotora_causal_explanation','KUS-04':'occ_origin_kushina_joint_residual_seal_closure','KUS-05':'occ_origin_kushina_gerotora_first_contact',
'KUR-01':'occ_origin_kurenai_bell_test_resolution','KUR-02':'occ_origin_kurenai_bell_test_resolution','IWA-01':'occ_origin_iwabee_training_ground_reshape_resolution','IWA-02':'occ_origin_iwabee_rogue_genin_response_resolution',
'MET-01':'occ_origin_metal_private_training_resolution','MET-02':'occ_origin_metal_pressured_performance_resolution','MET-03':'occ_origin_metal_protective_response_resolution','MET-04':'occ_origin_metal_inviting_genin_prior_contact',
'KAK-01':'occ_origin_kakashi_anbu_retrieval_resolution','KAK-02':'occ_origin_kakashi_anbu_retrieval_resolution','KAK-03':'occ_origin_kakashi_anbu_retrieval_resolution',
'OBI-01':null,'OBI-02':'occ_origin_obito_formal_training_entitlement_resolution','OBI-03':'occ_origin_obito_formal_training_entitlement_resolution','OBI-04':'occ_origin_obito_formal_training_entitlement_resolution','OBI-05':'occ_origin_obito_formal_training_entitlement_resolution'};
const obitoSources=new Set(['occ_origin_obito_furniture_assistance_resolution','occ_origin_obito_scattered_vegetables_resolution','occ_origin_obito_lost_academy_equipment_resolution','occ_origin_obito_overturned_delivery_resolution','occ_origin_obito_runaway_cart_resolution']);
function qualifies(row,f){switch(row){
case'HIN-01':return f.controlledSparCompleted===true;case'HIN-02':return f.youngerStudentChoice==='stay_and_watch'&&f.selfTaijutsuLearningOccurred===true;case'HIN-03':return['show_movement','explain_error'].includes(f.youngerStudentChoice);
case'IZU-01':return f.reliableEnvironmentalTrackingEstablished===true||f.falseTrailCorrectlyDiscovered===true;case'IZU-02':return f.interceptReachedByPrediction===true;case'IZU-03':return f.cooperatedWithAcademyStudents===true;case'IZU-04':return f.rogueGeninInterruptionResolvedByWasabiAction===true;
case'MIR-01':return f.substitutionVerifiedBeforeCheckpoint===true;case'MIR-02':return f.changedOrUnfamiliarChakraObserved===true;case'MIR-03':return f.personTravellingWithMiraiReachedCheckpointProtected===true&&f.substitutionVerifiedBeforeCheckpoint===false;
case'KUS-01':return f.qualifyingFuinjutsuWorkCompleted===true;case'KUS-02':return f.gerotoraCommunicatedOwnIdentity===true;case'KUS-03':return f.gerotoraExplainedResidualFormulaInference===true;case'KUS-04':return f.jointResidualSealClosureWithGerotora===true;case'KUS-05':return f.gerotoraFirstContactOccurred===true;
case'KUR-01':return f.bellTestOutcomeClass==='complete_loss';case'KUR-02':return['partial_loss','partial_win','complete_win'].includes(f.bellTestOutcomeClass);
case'IWA-01':return f.trainingGroundReshapeObjectiveCompletedByIwabee===true;case'IWA-02':return f.earthReleaseUsedToConstrainRogueGenin===true;
case'MET-01':return f.qualifyingPrivateTaijutsuOrConditioningWorkCompleted===true&&f.observerDiscoveryOccurredAfterQualifyingPrivateWork===true;case'MET-02':return['strong','mixed','rough'].includes(f.pressuredPerformanceClass);case'MET-03':return f.protectiveResponseAttempted===true;case'MET-04':return f.invitingGeninEncounterOccurred===true;
case'KAK-01':return['secured','lost','unresolved'].includes(f.packageDisposition);case'KAK-02':return['low','mixed','high'].includes(f.retrievalIntelligenceClass);case'KAK-03':return f.qualifyingParticipantOrCustodyInteractionOccurred===true;
case'OBI-01':return f.obitoCausalContributionEstablished===true;case'OBI-02':return f.formalTrainingEntitlement==='FULL';case'OBI-03':return f.formalTrainingEntitlement==='SUBSTANTIAL';case'OBI-04':return f.formalTrainingEntitlement==='REDUCED';case'OBI-05':return f.formalTrainingEntitlement==='MINIMAL';default:return false;}}
const ctx={console,Date,JSON,Object,Array,String,Number,Boolean,Set,Map,Math,globalThis:null,document:undefined,
playerData:{activityHistory:[],acquisition:{chronicleOriginVariantId:'academy_hinata',chronicleOrigin:{prologueCompleted:false}}},activityHistory:[],
cloneProgressionData:v=>v===undefined?undefined:JSON.parse(JSON.stringify(v)),savePlayerData:()=>true,getCurrentChronicleOccurrenceHistoryScope:()=>({kind:'origin_chronicle_occurrence'}),
unregisterStoryScene:id=>scenes.delete(id),registerStoryScene:def=>{def.beatMap=new Map((def.beats||[]).map(b=>[b.beatId,b]));scenes.set(def.sceneId,def);return{success:true,sceneId:def.sceneId};},getStorySceneDefinition:id=>scenes.get(id)||null,getActiveStorySceneRuntime:()=>active,
ensurePlayerAcquisitionState:()=>ctx.playerData.acquisition,openOverlay:()=>true,renderAlphaTailedBeastMissionCommand:()=>({success:true}),beginAlphaChronicleOriginPrologue:()=>({success:false,reason:'legacy'}),
completeChronicleOriginPrologue:(id,evidence)=>{ctx.playerData.acquisition.chronicleOrigin.prologueCompleted=true;completions.push({id,evidence});return{success:true,id,evidence};},
consumeStaticOriginSourceOccurrence:(row,record)=>{const expected=expectedSource[row];if(row==='OBI-01'){if(!obitoSources.has(record.sourceOccurrenceId))return{success:false,reason:'source_occurrence_id_not_authoritative'};}else if(expected!==record.sourceOccurrenceId)return{success:false,reason:'source_occurrence_id_not_authoritative'};if(!qualifies(row,record.fact||{}))return{success:false,reason:'qualification_predicate_not_satisfied'};const key=`${row}:${record.sourceOccurrenceId}`;const old=receipts.find(r=>r.key===key);if(old)return{success:true,idempotent:true,rowId:row};receipts.push({key,rowId:row,sourceOccurrenceId:record.sourceOccurrenceId,fact:record.fact});return{success:true,rowId:row};},
startStoryScene:(sceneId,opts)=>{const def=scenes.get(sceneId);if(!def)return{success:false,reason:'story_scene_not_registered'};active={sceneId,instanceId:`inst_${sceneId}`,beatId:def.entryBeatId,localContext:JSON.parse(JSON.stringify(opts.context||{})),processed:new Set()};enter();return{success:true,sceneId,beatId:active.beatId};}
};ctx.globalThis=ctx;vm.createContext(ctx);files.forEach(f=>vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f}));
function resolveReq(req,key){if(!req)return;const once=`${active.instanceId}:${active.beatId}:${key}:${req.requestId}`;if(active.processed.has(once))return;const out=req.resolve();if(!out||out.success!==true)throw new Error(`${req.requestId} failed: ${JSON.stringify(out)}`);active.processed.add(once);}
function enter(){const def=scenes.get(active.sceneId),beat=def.beatMap.get(active.beatId);(beat.onEnterConsequences||[]).forEach((r,i)=>resolveReq(r,`enter${i}`));}
function step(choiceId){const def=scenes.get(active.sceneId),beat=def.beatMap.get(active.beatId);if(choiceId){const c=(beat.choices||[]).find(x=>x.choiceId===choiceId);if(!c)throw new Error(`choice ${choiceId} missing @ ${active.sceneId}/${active.beatId}`);if(typeof c.availability==='function'){const a=c.availability();if(!a.available)throw new Error(`choice unavailable ${choiceId}: ${a.knownBlocker}`);}if(c.contextPatch)Object.assign(active.localContext,JSON.parse(JSON.stringify(c.contextPatch)));active.beatId=c.nextBeatId||beat.nextBeatId;enter();return;}if(beat.nextBeatId){active.beatId=beat.nextBeatId;enter();return;}if(beat.exitScene){(def.onCompleteConsequences||[]).forEach((r,i)=>resolveReq(r,`complete${i}`));active=null;return;}throw new Error(`no transition @ ${active.sceneId}/${active.beatId}`);}
function run(origin,choices){ctx.playerData.activityHistory=[];ctx.activityHistory=ctx.playerData.activityHistory;ctx.playerData.acquisition={chronicleOriginVariantId:origin,chronicleOrigin:{prologueCompleted:false}};active=null;const started=ctx.beginAlphaChronicleOriginPrologue();if(!started.success)throw new Error(`${origin} start failed ${JSON.stringify(started)}`);for(const c of choices){while(active){const b=scenes.get(active.sceneId).beatMap.get(active.beatId);if((b.choices||[]).length)break;if(b.nextBeatId)step(null);else break;}step(c);}while(active){const beat=scenes.get(active.sceneId).beatMap.get(active.beatId);if(beat.exitScene)step(null);else if(beat.nextBeatId&&!beat.choices?.length)step(null);else throw new Error(`path stopped @ ${origin}/${active.beatId}`);}if(!ctx.playerData.acquisition.chronicleOrigin.prologueCompleted)throw new Error(`${origin} did not complete`);}
run('academy_hinata',['attack_immediately','change_approach','remain_patient','stay_and_watch']);
run('academy_izuno',['predict_destination','intercept_prediction','trust_notice']);
run('academy_mirai',['ask_route','test_question','investigate_quietly']);
run('academy_kushina',['correct_formula','ask_who']);
run('academy_kurenai',['fake_clumsy','rush_bell','let_him_think_caught']);
run('academy_iwabee',['build_path','call_instructor','better_rest']);
run('academy_metal_lee',['demonstrate','redirect_dummy']);
run('academy_kakashi',['shadow_the_clerk','secure_package','proof']);
run('academy_obito',['furniture_continue','vegetables_continue','equipment_continue','delivery_continue','cart_continue','accept_full_training','hokage_still']);
const diag=ctx.runAlphaOriginScene32900Diagnostics();
const checks={diagPass:diag.pass,allNineCompleted:['academy_hinata','academy_izuno','academy_mirai','academy_kushina','academy_kurenai','academy_iwabee','academy_metal_lee','academy_kakashi','academy_obito'].every(id=>completions.some(c=>c.id===id)),
expectedCoreReceipts:['HIN-01','HIN-02','IZU-02','MIR-01','KUS-01','KUS-02','KUS-05','KUR-02','IWA-01','MET-01','MET-02','MET-03','MET-04','KAK-01','KAK-02','KAK-03','OBI-02'].every(id=>receipts.some(r=>r.rowId===id)),
obitoNoFakeDiversionReceipt:!receipts.some(r=>r.rowId==='OBI-01'),kakashiThreeIndependentMeanings:['KAK-01','KAK-02','KAK-03'].every(id=>receipts.some(r=>r.rowId===id)),browserGoldenClaimed:false};
const pass=Object.entries(checks).filter(([k])=>k!=='browserGoldenClaimed').every(([,v])=>v===true);console.log(JSON.stringify({pass,checks,receiptCount:receipts.length,completionCount:completions.length},null,2));if(!pass)process.exit(1);
