#!/usr/bin/env node
"use strict";
const fs=require("fs"),vm=require("vm"),path=require("path"),ROOT=path.resolve(__dirname,"..");
const scenes=new Map([["origin_academy_menma_prologue",{sceneId:"origin_academy_menma_prologue",entryBeatId:"menma",beats:[{beatId:"menma",exitScene:true}],beatMap:new Map([["menma",{beatId:"menma",exitScene:true}]])}]]);
let active=null,receipts=[],completions=[];
const playerData={activityHistory:[],acquisition:{chronicleOriginVariantId:"academy_hinata",chronicleOrigin:{prologueCompleted:false}}};let activityHistory=playerData.activityHistory;
const diversionIds=["occ_origin_obito_furniture_assistance_resolution","occ_origin_obito_scattered_vegetables_resolution","occ_origin_obito_lost_academy_equipment_resolution","occ_origin_obito_overturned_delivery_resolution","occ_origin_obito_runaway_cart_resolution"], diversionSet=new Set(diversionIds), entitlementId="occ_origin_obito_formal_training_entitlement_resolution";
const clone=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
function registerStoryScene(def){const c={...def,beats:def.beats||[]};c.beatMap=new Map(c.beats.map(b=>[b.beatId,b]));scenes.set(c.sceneId,c);return{success:true};}
function unregisterStoryScene(id){scenes.delete(id);return true;} function getStorySceneDefinition(id){return scenes.get(id)||null;} function getActiveStorySceneRuntime(){return active;}
function consumeStaticOriginSourceOccurrence(rowId,record){const key=rowId+"|"+record.sourceOccurrenceId;if(receipts.some(x=>x.key===key))return{success:true,idempotent:true,rowId};if(rowId==="OBI-01"&&(!diversionSet.has(record.sourceOccurrenceId)||record.fact?.obitoCausalContributionEstablished!==true))return{success:false,reason:"bad_obi01"};const ent={"OBI-02":"FULL","OBI-03":"SUBSTANTIAL","OBI-04":"REDUCED","OBI-05":"MINIMAL"}[rowId];if(ent&&record.fact?.formalTrainingEntitlement!==ent)return{success:false,reason:"bad_entitlement"};receipts.push({key,rowId});return{success:true,rowId};}
function completeChronicleOriginPrologue(id,evidence){playerData.acquisition.chronicleOrigin.prologueCompleted=true;completions.push({id,evidence});return{success:true};}
function beat(){return active?scenes.get(active.sceneId).beatMap.get(active.beatId):null;}
function resolve(req,key){if(!req)return;active.processed??=new Set();const token=active.beatId+"|"+key+"|"+req.requestId;if(active.processed.has(token))return;const r=req.resolve();if(!r||r.success!==true)throw Error("request failed "+JSON.stringify(r));active.processed.add(token);}
function enter(){const b=beat();if(!b)throw Error("missing beat "+active?.beatId);(b.onEnterConsequences||[]).forEach((r,i)=>resolve(r,"e"+i));}
function startStoryScene(sceneId,opts={}){const d=scenes.get(sceneId);active={sceneId,instanceId:"test_"+Date.now(),beatId:opts.entryBeatId||d.entryBeatId,localContext:clone(opts.context||{}),processed:new Set()};enter();return{success:true};}
function advanceStoryScene(choiceId=null){const b=beat();if(choiceId!==null){const c=(b.choices||[]).find(x=>x.choiceId===choiceId);if(!c)return{success:false,reason:"choice_missing",beat:b.beatId,choiceId};if(c.contextPatch)Object.assign(active.localContext,clone(c.contextPatch));active.beatId=c.nextBeatId||b.nextBeatId;enter();return{success:true};}if(b.nextBeatId){active.beatId=b.nextBeatId;enter();return{success:true};}if(b.exitScene){const d=scenes.get(active.sceneId);(d.onCompleteConsequences||[]).forEach((r,i)=>resolve(r,"c"+i));active=null;return{success:true};}return{success:false};}
const ctx={console,Date,JSON,Object,Array,String,Number,Boolean,Set,Map,Math,Error,globalThis:null,document:undefined,playerData,activityHistory,cloneProgressionData:clone,savePlayerData:()=>true,getCurrentChronicleOccurrenceHistoryScope:()=>({kind:"origin"}),registerStoryScene,unregisterStoryScene,getStorySceneDefinition,getActiveStorySceneRuntime,startStoryScene,advanceStoryScene,ensurePlayerAcquisitionState:()=>playerData.acquisition,consumeStaticOriginSourceOccurrence,completeChronicleOriginPrologue,registerSceneBackdropAssetPath:()=>({success:true}),openOverlay:()=>true,renderAlphaTailedBeastMissionCommand:()=>({success:true}),beginAlphaChronicleOriginPrologue:()=>({success:false,reason:"legacy"})};ctx.globalThis=ctx;vm.createContext(ctx);
for(const file of [
  path.join(ROOT,"runtime","alpha-origin-scenes-32900-core.js"),
  path.join(ROOT,"runtime","academy-wasabi-writing-golden-343.js"),
  path.join(ROOT,"runtime","alpha-origin-scenes-32900-a.js"),
  path.join(ROOT,"runtime","alpha-origin-scenes-32900-b.js"),
  path.join(ROOT,"runtime","alpha-origin-scenes-32900-c.js"),
  path.join(ROOT,"runtime","alpha-origin-scenes-32900-integrator.js")
])vm.runInContext(fs.readFileSync(file,"utf8"),ctx,{filename:file});
const sceneId=ctx.SC_ALPHA_ORIGIN_32900.sceneByVariant.academy_obito, keys=["furniture","vegetables","equipment","delivery","cart"], delays=[7,5,8,9,6], help=["furniture_help","vegetables_help","equipment_help","delivery_help","cart_help"], cont=["furniture_continue_final","vegetables_continue_final","equipment_continue_final","delivery_continue_final","cart_continue_final"], reflections=["reflection_keep_helping","reflection_take_training_seriously","reflection_find_balance","reflection_question_frame"];
const expected=d=>d<=5?"FULL":d<=14?"SUBSTANTIAL":d<=24?"REDUCED":d<=35?"MINIMAL":"NONE"; const assert=(v,m,x)=>{if(!v)throw Error(m+(x?": "+JSON.stringify(x):""));};
function reset(){playerData.activityHistory=[];ctx.activityHistory=activityHistory=playerData.activityHistory;playerData.acquisition={chronicleOriginVariantId:"academy_obito",chronicleOrigin:{prologueCompleted:false}};active=null;receipts=[];completions=[];}
function toChoice(){let g=0;while(active&&!(beat().choices||[]).length){assert(advanceStoryScene().success,"advance failed",beat());if(++g>80)throw Error("guard");}}
function run(mask,reflection=reflections[0]){reset();assert(ctx.beginAlphaChronicleOriginPrologue().success,"start failed");for(let i=0;i<5;i++){toChoice();assert(advanceStoryScene(mask&(1<<i)?help[i]:cont[i]).success,"diversion choice failed");}toChoice();assert(beat().beatId==="obi_reflect","reflection missing",beat());assert(advanceStoryScene(reflection).success,"reflection failed");while(active)assert(advanceStoryScene().success,"terminal failed",beat());const delay=delays.reduce((s,d,i)=>s+((mask&(1<<i))?d:0),0),ent=playerData.activityHistory.find(r=>r.sourceOccurrenceId===entitlementId),divs=playerData.activityHistory.filter(r=>diversionSet.has(r.sourceOccurrenceId)),self=playerData.activityHistory.find(r=>r.historyKey==="academy_obito_final_self_interpretation");return{mask,delay,expected:expected(delay),ent,divs,self,receipts:clone(receipts),completions:clone(completions)};}
assert(ctx.runAcademyObitoFinal331Diagnostics().pass,"diagnostics red",ctx.runAcademyObitoFinal331Diagnostics());
const def=getStorySceneDefinition(sceneId),choiceIds=def.beats.flatMap(b=>(b.choices||[]).map(c=>c.choiceId)),old=["furniture_carry_full","furniture_stabilize","furniture_continue","vegetables_collect_all","vegetables_clear_lane","vegetables_continue","equipment_search_full","equipment_check_likely_route","equipment_continue","delivery_right_and_reload","delivery_clear_passage","delivery_continue","cart_intercept","cart_warn_and_redirect","cart_continue","accept_full_training","timing_pending","hokage_still","faster_next","people_mattered","prove_it"];assert(old.every(x=>!choiceIds.includes(x)),"old choice active",choiceIds);
const matrix=[];for(let m=0;m<32;m++){const r=run(m,reflections[m%4]);assert(r.ent?.fact?.arrivalDelayMinutes===r.delay,"delay mismatch",r);assert(r.ent?.fact?.formalTrainingEntitlement===r.expected,"entitlement mismatch",r);assert(r.divs.length===5&&new Set(r.divs.map(x=>x.sourceOccurrenceId)).size===5,"diversion history collapsed",r.divs);for(let i=0;i<5;i++){const f=r.divs.find(x=>x.sourceOccurrenceId===diversionIds[i])?.fact,hit=!!(m&(1<<i));assert(f?.selectedIntent===(hit?"HELP":"CONTINUE"),"intent mismatch",f);assert(Number(f?.journeyDelayMinutes)===(hit?delays[i]:0),"delay fact mismatch",f);}assert(r.receipts.filter(x=>["OBI-02","OBI-03","OBI-04","OBI-05"].includes(x.rowId)).length===1,"training package not singular",r.receipts);assert(r.self?.fact?.selfInterpretationOnly===true&&r.self.fact.behaviourRewritten===false,"reflection not independent",r.self);assert(r.completions.length===1,"completion missing",r.completions);matrix.push({mask:m,delay:r.delay,entitlement:r.expected});}
assert(matrix[0].delay===0&&matrix[0].entitlement==="FULL","0-help not FULL",matrix[0]);assert(matrix[31].delay===35&&matrix[31].entitlement==="MINIMAL","5-help not MINIMAL",matrix[31]);assert(matrix[2].delay===5&&matrix[2].entitlement==="FULL"&&matrix[1].delay===7&&matrix[1].entitlement==="SUBSTANTIAL","same-count timing proof failed",{veg:matrix[2],furniture:matrix[1]});assert(matrix[3].delay===12&&matrix[3].entitlement==="SUBSTANTIAL"&&matrix[5].delay===15&&matrix[5].entitlement==="REDUCED","two-help timing proof failed",{fv:matrix[3],fe:matrix[5]});
reset();ctx.beginAlphaChronicleOriginPrologue();toChoice();advanceStoryScene("furniture_help");const req=beat().onEnterConsequences[0],h=playerData.activityHistory.length,p=receipts.length,again=req.resolve();assert(again.success&&Array.isArray(again.receipts)&&again.receipts.every(r=>r&&r.idempotent===true)&&playerData.activityHistory.length===h&&receipts.length===p,"idempotence failed",again);
reset();playerData.activityHistory.push({occurrenceId:diversionIds[0],sourceOccurrenceId:diversionIds[0],actorVariantId:"academy_obito",fact:{selectedResponse:"furniture_carry_full"},data:{}});ctx.beginAlphaChronicleOriginPrologue();const migrated=playerData.activityHistory.find(r=>r.sourceOccurrenceId===diversionIds[0]);assert(migrated?.fact?.selectedIntent==="HELP"&&migrated.fact.journeyDelayMinutes===7&&active.beatId==="obi_vegetables_intro","deterministic migration failed",{migrated,active});
reset();playerData.activityHistory.push({occurrenceId:diversionIds[0],sourceOccurrenceId:diversionIds[0],actorVariantId:"academy_obito",fact:{selectedResponse:"furniture_stabilize"},data:{}});ctx.beginAlphaChronicleOriginPrologue();assert(!playerData.activityHistory.some(r=>r.sourceOccurrenceId===diversionIds[0])&&active.beatId==="obi_depart","ambiguous migration did not restart",{history:playerData.activityHistory,active});
const interpretations=new Set(reflections.map(x=>run(0,x).self.fact.interpretationId));assert(interpretations.size===4,"route inferred reflection",Array.from(interpretations));
const graph=JSON.stringify(def);assert(!graph.includes("helpCount"),"helpCount introduced into registered Obito graph");assert(!graph.includes("grantSharingan")&&!graph.includes("sharinganUnlocked"),"Sharingan grant introduced into registered Obito graph");assert(!graph.includes("PL BATTLE")&&!graph.includes('"battle"'),"PL Battle introduced into registered Obito graph");
console.log(JSON.stringify({pass:true,issue:331,routesValidated:32,directTravel:matrix[0],allHelp:matrix[31],sameHelpCountProof:{vegetablesOnly:matrix[2],furnitureOnly:matrix[1]},twoHelpProof:{furnitureVegetables:matrix[3],furnitureEquipment:matrix[5]},migration:"GREEN",idempotence:"GREEN",reflectionIndependence:"GREEN",browserGoldenClaimed:false},null,2));
