"use strict";
const fs=require("fs");
const assert=require("assert");
const path=require("path");
const ROOT=process.cwd();
const read=p=>fs.readFileSync(path.join(ROOT,p),"utf8");
const consumer=read("runtime/alpha-kakashi-pakkun-interception-35300.js");
const loader=read("runtime/alpha-kakashi-final-origin-adapter-34100.js");
const core=read("runtime/alpha-story-decision-realisation-34000.js");
const factual=read("runtime/alpha-kakashi-factual-state-commit-34120.js");

assert(consumer.includes('PATCH_ID="alpha_kakashi_pakkun_interception_35300_v1_2026_09_17"'),"35300 patch identity missing");
assert(consumer.includes('ENTRY_BEAT="kak_get_closer_failure_stay_package_intercept"'),"35300 must bind the factual pursuit-success interception beat");
assert(consumer.includes('CONFIG="academy_kakashi_origin_battle_kakashi_pakkun_vs_amt"'),"35300 must use exact Pakkun + Kakashi vs AMT config");
assert(consumer.includes('BINDING.demand')&&consumer.includes('"AK_SA_009"'),"Demand must consume AK_SA_009");
assert(consumer.includes('DEMAND_PACKAGE_REFUSAL'),"Demand must commit fixed refusal before Battle");
assert(!consumer.includes("package-compliance"),"Demand must not invent package-compliance resolver");
assert(consumer.includes('currentHolderClass:"NEUTRAL_CONTESTED"'),"Take Him Down must make package neutral before Battle");
assert(consumer.includes('CORE.consumeNextAutonomy'),"Take Him Down must consume neutral participant-first autonomy");
assert(consumer.includes('dueAnchorIds:["AK_SA_011"]'),"Take Him Down must consume AK_SA_011 autonomy window");
assert(consumer.includes('autonomyPhase:"pre_battle"'),"mixed Story/Battle autonomy must explicitly identify the pre-Battle phase");
assert(core.includes('preBattleMixedAutonomy'),"34000 must allow only explicit pre-Battle mixed autonomy");
assert(core.includes('state.battleLive===true||(anchor.battleOwned===true&&!preBattleMixedAutonomy)'),"34000 must still block live Battle and pure Battle-owned autonomy");
assert(core.includes('autonomyPhaseRef:String(state.autonomyPhase||"pre_story")'),"34000 autonomy receipt must persist phase provenance");
assert(consumer.includes('selectionPolicyRef:"academy_kakashi.alpha.pakkun_exposed_objective_priority.v1"'),"Pakkun Alpha selection policy provenance missing");
assert(consumer.includes('participantAutonomyReceiptId'),"Take Him Down must persist autonomy receipt provenance");
assert(!consumer.includes('attemptAcademyKakashiPakkunBattleAction'),"pre-Battle autonomy must not grant a free Battle action");
assert(consumer.includes('priorPackageOccurrenceRef'),"Take Him Down defeat must consume prior committed package state");
assert(consumer.includes('packageOutcomeConsumedFromCommittedAutonomyState:!victory'),"Take Him Down defeat may not fabricate package recovery");
assert(consumer.includes('amtKnowsDownstreamDestination:false'),"Ask Destination must preserve AMT downstream ignorance");
assert(consumer.includes('packageSmugglerDisclosedDownstreamDestination:false'),"Ask Destination must preserve no downstream disclosure");
assert(!consumer.includes('verifiedActionableIntelligence:true'),"Ask Destination must not silently grant intelligence reward predicate");
assert(consumer.includes('decisionPointRef:"AK_SA_018_RECONVERGENCE"'),"Ask Destination must reconverge through a new semantic choice set");
assert(consumer.includes('KAK.openDecisionPoint("AK_SA_013"'),"victory must open existing four-way disposition semantic family");
assert(consumer.includes('availability:available(false,blocker)'),"disposition execution must remain fail-closed until its exact runtime owner is bound");
assert(consumer.includes('ownershipGranted:false')&&consumer.includes('nameKnowledgeGranted:false'),"temporary Pakkun participation must not leak ownership or name Knowledge");
assert(consumer.includes('browserGoldenClaimed:false'),"35300 must not claim browser Golden");
assert(loader.includes('runtime/alpha-kakashi-pakkun-interception-35300.js'),"34100 must production-load 35300");
assert(loader.includes('const BUILD="kakashi-final-20260917-18";'),"34100 build generation must advance to 18");
assert(core.includes('alpha-kakashi-final-origin-adapter-34100.js?sc=kakashi-final-20260917-18'),"34000 parent cache identity must request generation 18");
assert(factual.includes('interceptChoicesExactAndGuarded'),"34120 remains the fail-closed producer that 35300 deliberately releases");
console.log(JSON.stringify({pass:true,consumer:"35300",build:"kakashi-final-20260917-18",preBattleMixedAutonomy:true,browserGoldenClaimed:false},null,2));