#!/usr/bin/env node
"use strict";
const assert=require("assert");
const fs=require("fs");
const path=require("path");
const guard=require("./workforce_collision_guard_601.js");
const catalog=JSON.parse(fs.readFileSync(path.join(__dirname,"fixtures/workforce_protected_seams_601.json"),"utf8"));
const block=body=>guard.MARKER_START+"\n"+JSON.stringify(body,null,2)+"\n"+guard.MARKER_END;
function reservation(pr,workCell,lane,role="integration_owner",extra={}){return block({schema:guard.RESERVATION_SCHEMA,workCell,lane,role,issue:Number(String(workCell).replace(/\D/g,""))||601,integrationOwnerPr:role==="integration_owner"?pr:extra.integrationOwnerPr,reservedPaths:extra.reservedPaths||[],sharedSeams:extra.sharedSeams||[],sameCellOverlapPaths:extra.sameCellOverlapPaths||[]});}
const pr=(number,title,headRef,changedFiles,body="",state="open")=>({number,title,headRef,changedFiles,body,state});
const run=(targetPr,openPrs)=>guard.evaluateSnapshot({targetPr,openPrs},catalog);
let r;
r=run(100,[pr(100,"[CODING] A","coding/a",["runtime/a.js"],reservation(100,"#100","A","integration_owner",{reservedPaths:["runtime/a.js"]})),pr(101,"[CODING] B","coding/b",["runtime/b.js"],reservation(101,"#101","B","integration_owner",{reservedPaths:["runtime/b.js"]}))]);assert.strictEqual(r.pass,true,JSON.stringify(r));
r=run(110,[pr(110,"[CODING] A","coding/a",["runtime/shared.js"],reservation(110,"#110","A")),pr(111,"[CODING] B","coding/b",["runtime/shared.js"],reservation(111,"#111","B"))]);assert.strictEqual(r.pass,true,JSON.stringify(r));assert(r.findings.some(x=>x.code==="CROSS_CELL_PRODUCTION_COLLISION"&&x.severity==="WARN"));
r=run(120,[pr(120,"[CODING] Integrator","coding/cell-integrator",["runtime/shared.js"],reservation(120,"#120","I","integration_owner",{sameCellOverlapPaths:["runtime/shared.js"]})),pr(121,"[CODING] Builder","coding/cell-builder",["runtime/shared.js"],reservation(121,"#120","J","builder",{integrationOwnerPr:120,sameCellOverlapPaths:["runtime/shared.js"]}))]);assert.strictEqual(r.pass,true,JSON.stringify(r));assert(r.findings.some(x=>x.code==="DECLARED_SAME_CELL_OVERLAP"&&x.severity==="INFO"));
r=run(130,[pr(130,"[CODING] Integrator","coding/cell-integrator",["runtime/shared.js"],reservation(130,"#130","I")),pr(131,"[CODING] Builder","coding/cell-builder",["runtime/shared.js"],reservation(131,"#130","J","builder",{integrationOwnerPr:130}))]);assert.strictEqual(r.pass,true,JSON.stringify(r));assert(r.findings.some(x=>x.code==="UNDECLARED_SAME_CELL_OVERLAP"&&x.severity==="WARN"));
r=run(140,[pr(140,"[CODING] Target","coding/target",["index.html"],reservation(140,"#140","I")),pr(141,"[CODING] Owner","coding/owner",["runtime/owner.js"],reservation(141,"#141","A","integration_owner",{sharedSeams:["production_loader"]}))]);assert.strictEqual(r.pass,false);assert(r.findings.some(x=>x.code==="PROTECTED_SEAM_RESERVED_TO_OTHER"&&x.seam==="production_loader"));
r=run(150,[pr(150,"[CODING] Owner","coding/owner",["index.html"],reservation(150,"#150","A","integration_owner",{sharedSeams:["production_loader"]}))]);assert.strictEqual(r.pass,true,JSON.stringify(r));assert.strictEqual(r.protectedSeamOwners.production_loader.state,"CLAIMED");
r=run(160,[pr(160,"[CODING] Owner 1","coding/owner1",["index.html"],reservation(160,"#160","A","integration_owner",{sharedSeams:["production_loader"]})),pr(161,"[CODING] Owner 2","coding/owner2",["runtime/other.js"],reservation(161,"#161","B","integration_owner",{sharedSeams:["production_loader"]}))]);assert.strictEqual(r.pass,false);assert(r.findings.some(x=>x.code==="PROTECTED_SEAM_AMBIGUOUS_OWNER"));
r=run(170,[pr(170,"[CODING] Target","coding/target",["runtime/shared.js"],reservation(170,"#170","A")),pr(171,"[CODING] Bad","coding/bad",["runtime/shared.js"],guard.MARKER_START+"\n{bad json}\n"+guard.MARKER_END)]);assert.strictEqual(r.pass,false);assert(r.findings.some(x=>x.code==="UNCLASSIFIED_PRODUCTION_COLLISION"));
r=run(180,[pr(180,"[CODING] Builder","coding/builder",["runtime/a.js"],reservation(180,"#180","J","builder",{integrationOwnerPr:999,reservedPaths:["runtime/a.js"]}))]);assert.strictEqual(r.pass,false);assert(r.findings.some(x=>x.code==="MALFORMED_RESERVATION"));
r=run(190,[pr(190,"[CODING] Tooling","coding/601-tooling",["tools/workforce_collision_guard_601.js",".github/workflows/issue-601-workforce-collision.yml"],reservation(190,"#601-S0.5","I")),pr(191,"[CODING] Existing","coding/existing",["runtime/a.js"],reservation(191,"#191","A"))]);assert.strictEqual(r.pass,true,JSON.stringify(r));assert.strictEqual(r.targetProductionFiles.length,0);
r=run(200,[pr(200,"[CODING] malformed types","coding/malformed-types",["runtime/a.js"],block({schema:guard.RESERVATION_SCHEMA,workCell:"#200",lane:"I",role:"integration_owner",issue:200,integrationOwnerPr:200,reservedPaths:"runtime/a.js",sharedSeams:"production_loader",sameCellOverlapPaths:"runtime/a.js"}))]);assert.strictEqual(r.pass,false);assert(r.findings.some(x=>x.code==="MALFORMED_RESERVATION"&&x.severity==="BLOCK"));
r=run(210,[pr(210,"[CODING] target","coding/target",["runtime/claimed-by-malformed-owner.js"],reservation(210,"#210","I")),pr(211,"[CODING] malformed owner","coding/malformed-owner",["runtime/unrelated.js"],block({schema:guard.RESERVATION_SCHEMA,workCell:"#211",lane:"J",role:"integration_owner",issue:211,integrationOwnerPr:211,reservedPaths:["runtime/claimed-by-malformed-owner.js"],sharedSeams:[],sameCellOverlapPaths:"not-an-array"}))]);assert.strictEqual(r.pass,false,JSON.stringify(r));assert(r.findings.some(x=>x.code==="MALFORMED_RESERVED_PATH_CLAIM"&&x.path==="runtime/claimed-by-malformed-owner.js"));
r=run(220,[pr(220,"[CODING] wildcard target","coding/wildcard-target",["runtime/foo.js"],reservation(220,"#220","I")),pr(221,"[CODING] wildcard owner","coding/wildcard-owner",["runtime/unrelated.js"],reservation(221,"#221","J","integration_owner",{reservedPaths:["runtime/*.js"]}))]);assert.strictEqual(r.pass,false);assert(r.findings.some(x=>x.code==="RESERVED_PATH_VIOLATION"));
r=run(230,[pr(230,"[CODING] recursive target","coding/recursive-target",["runtime/deep/foo.js"],reservation(230,"#230","I")),pr(231,"[CODING] recursive owner","coding/recursive-owner",["runtime/unrelated.js"],reservation(231,"#231","J","integration_owner",{reservedPaths:["runtime/**"]}))]);assert.strictEqual(r.pass,false);assert(r.findings.some(x=>x.code==="RESERVED_PATH_VIOLATION"));
console.log(JSON.stringify({pass:true,issue:601,slice:"S0.5-collision-reservation",cases:{cleanNoFalsePositive:true,crossCellCollisionWarned:true,declaredSameCellOverlapDistinguished:true,undeclaredSameCellOverlapWarned:true,protectedSeamOtherOwnerBlocked:true,protectedSeamExactOwnerAllowed:true,ambiguousProtectedSeamOwnerBlocked:true,malformedCollisionFailsClosed:true,staleIntegrationOwnerFailsClosed:true,toolingOnlyCandidateDoesNotSelfBlock:true,wrongArrayTypesFailClosed:true,malformedForeignClaimFailsClosed:true,singleStarWildcardEnforced:true,doubleStarWildcardEnforced:true},productionRuntimeTouched:false,browserGoldenClaimed:false},null,2));
