#!/usr/bin/env node
"use strict";
const fs=require("fs");
const path=require("path");
const RESERVATION_SCHEMA="sc.workforce-reservation.601.v1";
const SEAM_SCHEMA="sc.workforce-protected-seams.601.v1";
const MARKER_START="<!-- SC-WORKFORCE-RESERVATION-601";
const MARKER_END="SC-WORKFORCE-RESERVATION-601 -->";
const norm=v=>String(v||"").replace(/\\/g,"/").replace(/^\.\//,"").trim();
function parseArgs(argv){const out={};for(let i=0;i<argv.length;i++){const t=argv[i];if(!t.startsWith("--"))continue;const k=t.slice(2),n=argv[i+1];if(!n||n.startsWith("--"))out[k]=true;else{out[k]=n;i++;}}return out;}
function wildcardToRegExp(pattern){const p=norm(pattern);if(!p)throw new Error("empty path pattern");let s="^";for(let i=0;i<p.length;i++){const c=p[i];if(c==="*"&&p[i+1]==="*"){s+=".*";i++;}else if(c==="*")s+="[^/]*";else s+=/[\\^$.*+?()[\]{}|]/.test(c)?"\\"+c:c;}return new RegExp(s+"$");}
const matchesPattern=(file,pattern)=>wildcardToRegExp(pattern).test(norm(file));
const isDocumentationOnly=file=>/^Documentation\//.test(norm(file))||/^README(?:\.md)?$/i.test(norm(file))||/^CHANGELOG(?:\.md)?$/i.test(norm(file));
const isCoordinationTooling=file=>/^tools\//.test(norm(file))||/^\.github\/workflows\//.test(norm(file));
const isProductionPath=file=>!!norm(file)&&!isDocumentationOnly(file)&&!isCoordinationTooling(file);
function isCodingPr(pr){const title=String(pr.title||""),ref=String(pr.headRef||(pr.head&&pr.head.ref)||"");return /\[(?:CODING|QA|RUNTIME|WORK-CELL)\]/i.test(title)||/^(?:coding|qa)\//i.test(ref);}
function parseReservationBlock(body){const text=String(body||""),starts=[];let pos=0;while(true){const i=text.indexOf(MARKER_START,pos);if(i<0)break;starts.push(i);pos=i+MARKER_START.length;}if(!starts.length)return{present:false,value:null,errors:[]};if(starts.length>1)return{present:true,value:null,errors:["multiple reservation blocks"]};const start=starts[0]+MARKER_START.length,end=text.indexOf(MARKER_END,start);if(end<0)return{present:true,value:null,errors:["reservation block missing closing marker"]};if(text.indexOf(MARKER_END,end+MARKER_END.length)>=0)return{present:true,value:null,errors:["multiple reservation closing markers"]};try{return{present:true,value:JSON.parse(text.slice(start,end).trim()),errors:[]};}catch(e){return{present:true,value:null,errors:["reservation JSON parse failed: "+e.message]};}}
function arrayField(raw,key,errors,normalizer){if(!Array.isArray(raw[key])){errors.push(key+" must be an array");return [];}const out=[];for(const x of raw[key]){if(typeof x!=="string"||!x.trim()){errors.push(key+" entries must be non-empty strings");continue;}out.push(normalizer(x));}return[...new Set(out)];}
function visibleClaims(raw,key,normalizer){if(!raw||typeof raw!=="object"||Array.isArray(raw))return[];const v=raw[key];if(Array.isArray(v))return[...new Set(v.filter(x=>typeof x==="string"&&x.trim()).map(normalizer))];if(typeof v==="string"&&v.trim())return[normalizer(v)];return[];}
function validateReservation(raw,prNumber){const errors=[];if(!raw||typeof raw!=="object"||Array.isArray(raw))return{valid:false,errors:["reservation must be an object"],value:null};const value={schema:raw.schema,workCell:typeof raw.workCell==="string"?raw.workCell.trim():"",lane:typeof raw.lane==="string"?raw.lane.trim():"",role:typeof raw.role==="string"?raw.role.trim():"",issue:Number(raw.issue),integrationOwnerPr:raw.integrationOwnerPr==null?null:Number(raw.integrationOwnerPr),reservedPaths:arrayField(raw,"reservedPaths",errors,norm),sharedSeams:arrayField(raw,"sharedSeams",errors,x=>x.trim()),sameCellOverlapPaths:arrayField(raw,"sameCellOverlapPaths",errors,norm)};if(value.schema!==RESERVATION_SCHEMA)errors.push("schema must equal "+RESERVATION_SCHEMA);if(!value.workCell)errors.push("workCell is required and must be a non-empty string");if(!value.lane)errors.push("lane is required and must be a non-empty string");if(!value.role)errors.push("role is required and must be a non-empty string");if(!Number.isInteger(value.issue)||value.issue<=0)errors.push("issue must be a positive integer");if(value.integrationOwnerPr==null)errors.push("integrationOwnerPr is required");else if(!Number.isInteger(value.integrationOwnerPr)||value.integrationOwnerPr<=0)errors.push("integrationOwnerPr must be a positive integer");if(value.role==="integration_owner"&&value.integrationOwnerPr!==Number(prNumber))errors.push("integration_owner integrationOwnerPr must equal its own PR number");if(value.sharedSeams.length&&value.role!=="integration_owner")errors.push("only integration_owner may claim sharedSeams");for(const p of [...value.reservedPaths,...value.sameCellOverlapPaths])try{wildcardToRegExp(p);}catch(e){errors.push("invalid path pattern "+p+": "+e.message);}return{valid:!errors.length,errors,value};}
function loadSeamCatalog(catalog){if(!catalog||catalog.schema!==SEAM_SCHEMA||!Array.isArray(catalog.seams))throw new Error("protected seam catalog must use schema "+SEAM_SCHEMA+" with seams[]");const seen=new Set();return catalog.seams.map((row,i)=>{const id=String(row&&row.id||"").trim(),patterns=Array.isArray(row&&row.patterns)?row.patterns.map(norm).filter(Boolean):[];if(!id)throw new Error("protected seam row "+i+" missing id");if(seen.has(id))throw new Error("duplicate protected seam id "+id);seen.add(id);if(!patterns.length)throw new Error("protected seam "+id+" must declare patterns");patterns.forEach(wildcardToRegExp);return{id,description:String(row.description||""),patterns};});}
function normalizePr(raw){const number=Number(raw.number);if(!Number.isInteger(number)||number<=0)throw new Error("PR number must be a positive integer");return{number,title:String(raw.title||""),body:String(raw.body||""),state:String(raw.state||"open"),headRef:String(raw.headRef||(raw.head&&raw.head.ref)||""),headSha:String(raw.headSha||(raw.head&&raw.head.sha)||""),changedFiles:[...new Set((Array.isArray(raw.changedFiles)?raw.changedFiles:[]).map(norm).filter(Boolean))].sort()};}
function preparePr(raw,openNumbers){const pr=normalizePr(raw),parsed=parseReservationBlock(pr.body);let reservation=null,errors=[...parsed.errors];if(parsed.present&&parsed.value){const checked=validateReservation(parsed.value,pr.number);reservation=checked.value;errors.push(...checked.errors);if(reservation&&reservation.integrationOwnerPr!=null&&!openNumbers.has(reservation.integrationOwnerPr))errors.push("integrationOwnerPr #"+reservation.integrationOwnerPr+" is not an open PR");}return{...pr,reservationPresent:parsed.present,reservationRaw:parsed.value,reservation,reservationErrors:errors,reservationValid:parsed.present&&!errors.length,visibleReservedPathClaims:visibleClaims(parsed.value,"reservedPaths",norm),visibleSharedSeamClaims:visibleClaims(parsed.value,"sharedSeams",x=>x.trim())};}
function reservationPatternHits(pr,file){const patterns=pr.reservationValid?pr.reservation.reservedPaths:pr.visibleReservedPathClaims;return patterns.filter(p=>{try{return matchesPattern(file,p);}catch{return false;}});}
function sameCellOverlapDeclared(a,b,file){return !!(a.reservationValid&&b.reservationValid&&a.reservation.workCell===b.reservation.workCell&&(a.reservation.sameCellOverlapPaths.some(p=>matchesPattern(file,p))||b.reservation.sameCellOverlapPaths.some(p=>matchesPattern(file,p))));}
const finding=(severity,code,data)=>({severity,code,...data});
function evaluateSnapshot(snapshot,catalog){const targetNumber=Number(snapshot.targetPr);if(!Number.isInteger(targetNumber)||targetNumber<=0)throw new Error("snapshot.targetPr must be a positive integer");if(!Array.isArray(snapshot.openPrs))throw new Error("snapshot.openPrs must be an array");const base=snapshot.openPrs.map(normalizePr).filter(pr=>pr.state==="open"),openNumbers=new Set(base.map(pr=>pr.number)),prs=base.map(pr=>preparePr(pr,openNumbers)),target=prs.find(pr=>pr.number===targetNumber);if(!target)throw new Error("target PR #"+targetNumber+" is not present in openPrs");const coding=prs.filter(pr=>isCodingPr(pr)||pr.number===targetNumber),seams=loadSeamCatalog(catalog),findings=[];
for(const pr of coding)if(pr.reservationPresent&&!pr.reservationValid)findings.push(finding(pr.number===target.number?"BLOCK":"WARN","MALFORMED_RESERVATION",{pr:pr.number,errors:pr.reservationErrors}));
const owners={};for(const seam of seams){const valid=coding.filter(pr=>pr.reservationValid&&pr.reservation.sharedSeams.includes(seam.id)),bad=coding.filter(pr=>!pr.reservationValid&&pr.reservationPresent&&pr.visibleSharedSeamClaims.includes(seam.id));if(bad.length)owners[seam.id]={state:"MALFORMED",owners:valid.map(pr=>({pr:pr.number,lane:pr.reservation.lane,workCell:pr.reservation.workCell})),malformedClaimers:bad.map(pr=>({pr:pr.number,errors:pr.reservationErrors}))};else if(!valid.length)owners[seam.id]={state:"UNCLAIMED",owners:[]};else if(valid.length===1)owners[seam.id]={state:"CLAIMED",owners:[{pr:valid[0].number,lane:valid[0].reservation.lane,workCell:valid[0].reservation.workCell}]};else owners[seam.id]={state:"AMBIGUOUS",owners:valid.map(pr=>({pr:pr.number,lane:pr.reservation.lane,workCell:pr.reservation.workCell}))};}
for(const file of target.changedFiles)for(const seam of seams){if(!seam.patterns.some(p=>matchesPattern(file,p)))continue;const owner=owners[seam.id];if(owner.state==="UNCLAIMED")findings.push(finding("BLOCK","PROTECTED_SEAM_UNCLAIMED",{path:file,seam:seam.id,targetPr:target.number}));else if(owner.state==="AMBIGUOUS")findings.push(finding("BLOCK","PROTECTED_SEAM_AMBIGUOUS_OWNER",{path:file,seam:seam.id,targetPr:target.number,owners:owner.owners}));else if(owner.state==="MALFORMED")findings.push(finding("BLOCK","PROTECTED_SEAM_MALFORMED_OWNER_METADATA",{path:file,seam:seam.id,targetPr:target.number,owners:owner.owners,malformedClaimers:owner.malformedClaimers}));else if(owner.owners[0].pr!==target.number)findings.push(finding("BLOCK","PROTECTED_SEAM_RESERVED_TO_OTHER",{path:file,seam:seam.id,targetPr:target.number,owner:owner.owners[0]}));}
for(const other of coding){if(other.number===target.number)continue;const overlap=target.changedFiles.filter(file=>isProductionPath(file)&&other.changedFiles.includes(file));for(const file of overlap){const malformed=(target.reservationPresent&&!target.reservationValid)||(other.reservationPresent&&!other.reservationValid);if(malformed)findings.push(finding("BLOCK","UNCLASSIFIED_PRODUCTION_COLLISION",{path:file,targetPr:target.number,otherPr:other.number,targetReservationValid:target.reservationValid,otherReservationValid:other.reservationValid,reason:"malformed reservation metadata prevents safe collision classification"}));else if(target.reservationValid&&other.reservationValid&&target.reservation.workCell===other.reservation.workCell){const declared=sameCellOverlapDeclared(target,other,file);findings.push(finding(declared?"INFO":"WARN",declared?"DECLARED_SAME_CELL_OVERLAP":"UNDECLARED_SAME_CELL_OVERLAP",{path:file,targetPr:target.number,otherPr:other.number,workCell:target.reservation.workCell}));}else findings.push(finding("WARN",target.reservationValid&&other.reservationValid?"CROSS_CELL_PRODUCTION_COLLISION":"UNCLASSIFIED_PRODUCTION_COLLISION",{path:file,targetPr:target.number,otherPr:other.number,targetWorkCell:target.reservationValid?target.reservation.workCell:null,otherWorkCell:other.reservationValid?other.reservation.workCell:null}));}
for(const file of target.changedFiles){const hits=reservationPatternHits(other,file);if(!hits.length)continue;if(!other.reservationValid){findings.push(finding("BLOCK","MALFORMED_RESERVED_PATH_CLAIM",{path:file,targetPr:target.number,ownerPr:other.number,ownerPatterns:hits,ownerErrors:other.reservationErrors}));continue;}if(!target.reservationValid){findings.push(finding("BLOCK","RESERVED_PATH_TARGET_UNDECLARED",{path:file,targetPr:target.number,ownerPr:other.number,ownerPatterns:hits}));continue;}if(target.reservation.workCell===other.reservation.workCell){const declared=sameCellOverlapDeclared(target,other,file);findings.push(finding(declared?"INFO":"WARN",declared?"DECLARED_SAME_CELL_RESERVED_PATH_OVERLAP":"SAME_CELL_RESERVED_PATH_OVERLAP",{path:file,targetPr:target.number,ownerPr:other.number,workCell:target.reservation.workCell,ownerPatterns:hits}));}else findings.push(finding("BLOCK","RESERVED_PATH_VIOLATION",{path:file,targetPr:target.number,ownerPr:other.number,ownerLane:other.reservation.lane,ownerWorkCell:other.reservation.workCell,ownerPatterns:hits}));}}
if(target.reservationValid&&target.reservation.integrationOwnerPr!==target.number){const owner=coding.find(pr=>pr.number===target.reservation.integrationOwnerPr);if(!owner||!owner.reservationValid||owner.reservation.workCell!==target.reservation.workCell||owner.reservation.role!=="integration_owner")findings.push(finding("BLOCK","STALE_OR_INVALID_INTEGRATION_OWNER",{targetPr:target.number,integrationOwnerPr:target.reservation.integrationOwnerPr,workCell:target.reservation.workCell}));}
const blocks=findings.filter(x=>x.severity==="BLOCK"),warns=findings.filter(x=>x.severity==="WARN");return{pass:!blocks.length,issue:601,slice:"S0.5-collision-reservation",targetPr:target.number,targetChangedFiles:target.changedFiles,targetProductionFiles:target.changedFiles.filter(isProductionPath),openCodingPrCount:coding.length,protectedSeamOwners:owners,counts:{block:blocks.length,warn:warns.length,info:findings.filter(x=>x.severity==="INFO").length},findings};}
async function githubJson(url,token){const headers={Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","User-Agent":"sc-workforce-collision-601"};if(token)headers.Authorization="Bearer "+token;const r=await fetch(url,{headers});if(!r.ok)throw new Error("GitHub API "+r.status+" for "+url+": "+await r.text());return r.json();}
async function fetchPaged(url,token){const rows=[];for(let page=1;page<=20;page++){const batch=await githubJson(url+(url.includes("?")?"&":"?")+"per_page=100&page="+page,token);if(!Array.isArray(batch))throw new Error("expected array from "+url);rows.push(...batch);if(batch.length<100)break;}return rows;}
async function buildLiveSnapshot(repo,targetPr,token){if(!/^[^/]+\/[^/]+$/.test(repo||""))throw new Error("--repo owner/name is required for live mode");const n=Number(targetPr);if(!Number.isInteger(n)||n<=0)throw new Error("--target-pr must be a positive integer");const base="https://api.github.com/repos/"+repo,pulls=await fetchPaged(base+"/pulls?state=open",token),openPrs=[];for(const pr of pulls){const candidate={number:pr.number,title:pr.title,body:pr.body||"",state:pr.state,headRef:pr.head&&pr.head.ref||"",headSha:pr.head&&pr.head.sha||""};if(!isCodingPr(candidate)&&Number(pr.number)!==n)continue;candidate.changedFiles=(await fetchPaged(base+"/pulls/"+pr.number+"/files",token)).map(row=>row.filename);openPrs.push(candidate);}return{targetPr:n,openPrs};}
function writeReport(file,result){if(!file)return;fs.mkdirSync(path.dirname(path.resolve(file)),{recursive:true});fs.writeFileSync(file,JSON.stringify(result,null,2)+"\n");}
function writeGithubOutput(file,result){if(!file)return;const rows={pass:String(result.pass),block_count:String(result.counts.block),warn_count:String(result.counts.warn),info_count:String(result.counts.info)};fs.appendFileSync(file,Object.entries(rows).map(([k,v])=>k+"="+v).join("\n")+"\n");}
async function main(){const args=parseArgs(process.argv.slice(2)),catalog=JSON.parse(fs.readFileSync(args.catalog||"tools/fixtures/workforce_protected_seams_601.json","utf8"));let snapshot;if(args.snapshot)snapshot=JSON.parse(fs.readFileSync(args.snapshot,"utf8"));else if(args.live)snapshot=await buildLiveSnapshot(args.repo||process.env.GITHUB_REPOSITORY,args["target-pr"]||process.env.PR_NUMBER,process.env.GITHUB_TOKEN||"");else throw new Error("use --snapshot <file> or --live --target-pr <number>");const result=evaluateSnapshot(snapshot,catalog);writeReport(args["json-out"],result);writeGithubOutput(args["github-output"]||process.env.GITHUB_OUTPUT,result);process.stdout.write(JSON.stringify(result,null,2)+"\n");if(!result.pass&&!args["report-only"])process.exitCode=1;}
if(require.main===module)main().catch(e=>{console.error("[workforce-collision-601] "+e.stack);process.exit(2);});
module.exports={RESERVATION_SCHEMA,SEAM_SCHEMA,MARKER_START,MARKER_END,norm,matchesPattern,isProductionPath,isCodingPr,parseReservationBlock,validateReservation,loadSeamCatalog,evaluateSnapshot,buildLiveSnapshot};
